apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: flask-taufik
  namespace: taufik-devops
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: flaskapp
  updatePolicy:
    updateMode: "Auto"

